[package]
name = "cargo-repl"
version = "0.0.1"
authors = ["richard <richard>"]
edition = "2018"
license = "Apache-2.0"
description = "a repl component for cargo"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
